---
image: atlassian/default-image:latest

pipelines:
  branches:
    main:
      - step:
          name: Publish App to GitHub
          script:
            - git config --global user.email "ci-bot@ci.local"
            - git config --global user.name "Bitbucket CI Bot"
            - git init
            - git checkout -B main
            - |
              GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com"
              REPO_PATH="opennodezz/nextpos_printing.git"
              git remote add github \
                "${GITHUB_URL}/${REPO_PATH}"
            # Remove unwanted files before staging
            - |
              rm -f bitbucket-pipelines.yml \
                README_DEV.md \
                README.md \
                ReleaseChecklist.md
            - git add .
            - |
              git commit -m "CI: publish app from Bitbucket $(date)" \
                --allow-empty
            - git push github main --force
