---
image: atlassian/default-image:latest

pipelines:
  branches:
    main:
      - step:
          name: Publish App to GitHub
          script:
            - git config --global user.email "ci-bot@yourdomain.com"
            - git config --global user.name "Bitbucket CI Bot"

            - mkdir publish
            - cp -r nextpos_printing/* publish/
            - cd publish
            - git init
            - git checkout -b main

            # Define GitHub URL in a variable to shorten line length
            - |
              GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/opennodezz"
              git remote add github "${GITHUB_URL}/nextpos_printing.git"

            - git add .

            # Commit message broken into multiple lines (<80 chars each)
            - |
              git commit -m "CI: publish app from Bitbucket $(date)" \
                --allow-empty

            - git push github main --force
