---
# Bitbucket pipeline to publish only the "nextpos_printing" app folder
# into GitHub as a proper Frappe app repo.
# This ensures that GitHub repo root contains setup.py, MANIFEST.in, etc.

image: atlassian/default-image:latest   # Default build image from Atlassian

pipelines:
  branches:
    main:   # Trigger this pipeline when pushing to Bitbucket "main" branch
      - step:
          name: Publish App Folder to GitHub   # Name visible in Bitbucket UI
          script:
            # 1. Configure Git user identity for commits
            - git config --global user.email "ci-bot@yourdomain.com"
            - git config --global user.name "Bitbucket CI Bot"

            # 2. Create a clean working directory for publish
            - mkdir publish

            # 3. Copy ONLY the app folder into this directory
            # (avoids copying readme/pipeline files from repo root)
            - cp -r nextpos_printing/* publish/

            # 4. Initialize a fresh Git repo with just the app content
            - cd publish
            - git init
            - git checkout -b main

            # 5. Add GitHub as remote, using token for authentication
            # (store token securely in Bitbucket repo variables)
            - >
              git remote add github
              https://x-access-token:${NEXTPOS_PRINTING_PA_TOKEN_GITHUB}@github.com/opennodezz/nextpos_printing.git

            # 6. Stage all files in the publish directory
            - git add .

            # 7. Commit the app snapshot (skip error if no changes)
            - >
              git commit -m "CI: publish app from Bitbucket $(date)" \
              || echo "No changes to commit"

            # 8. Force-push to GitHub main branch
            - git push github main --force
