image: atlassian/default-image:latest

pipelines:
  branches:
    main:   # This section runs whenever you push to 'main'
      - step:
          name: Mirror to GitHub
          script:
            # Set up a Git user for the pipeline (needed for pushes)
            - git config --global user.email "ci-bot@yourdomain.com"
            - git config --global user.name "Bitbucket CI Bot"

            # Add GitHub as a remote (using your GitHub token for auth)
            - git remote add github https://x-access-token:${NEXTPOS_PRINTING_PA_TOKEN_GITHUB}@github.com/opennodezz/nextpos_printing.git

            # Make sure we’re on the right branch
            - git checkout main

            # Push code from Bitbucket → GitHub
            - git push github main --force
