---
image: atlassian/default-image:latest

pipelines:
  branches:
    main:
      - step:
          name: Publish App to GitHub
          script:
            - git config --global user.email "ci-bot@yourdomain.com"
            - git config --global user.name "Bitbucket CI Bot"

            # Copy the whole app folder (including inner package) into clean repo
            - mkdir publish
            - cp -r nextpos_printing/* publish/

            # remove unwanted files
            - rm -f publish/bitbucket-pipelines.yml
            - rm -f publish/README_DEV.md
            - rm -f publish/README.md
            - rm -f publish/ReleaseChecklist.md
            
            - cd publish
            - git init
            - git checkout -b main

            # Short variable keeps line length <80 chars
            - |
              GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com"
              git remote add github \
                "${GITHUB_URL}/opennodezz/nextpos_printing.git"

            - git add .
            - |
              git commit -m "CI: publish app from Bitbucket $(date)" \
                --allow-empty

            - git push github main --force
