---
image: atlassian/default-image:latest

pipelines:
  branches:
    main:
      - step:
          name: Publish App to GitHub
          script:
            - git config --global user.email "ci-bot@ci.local"
            - git config --global user.name "Bitbucket CI Bot"
            - mkdir publish
            - cp -r nextpos_printing/* publish/
            - rm -f publish/bitbucket-pipelines.yml
            - rm -f publish/README_DEV.md
            - rm -f publish/README.md
            - rm -f publish/ReleaseChecklist.md
            - cd publish
            - git init
            - git checkout -b main
            - |
              GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com"
              REPO_PATH="opennodezz/nextpos_printing.git"
              git remote add github "${GITHUB_URL}/${REPO_PATH}"
            - git add .
            - |
              git commit -m "CI: publish app from Bitbucket $(date)" \
                --allow-empty
            - git push github main --force
