---
image: atlassian/default-image:latest

pipelines:
  branches:
    main:
      - step:
          name: Publish App to GitHub
          script:
            - git config --global user.email "ci-bot@ci.local"
            - git config --global user.name "Bitbucket CI Bot"
            # Init a fresh repo for publishing
            - git init
            - git checkout -B main
            - |
              GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com"
              REPO_PATH="opennodezz/nextpos_printing.git"
              git remote add github "${GITHUB_URL}/${REPO_PATH}"
            # Use .gitignore_publish to exclude files when staging
            - |
              for file in $(find . -type f \
                | sed 's|^\./||' \
                | grep -v -f .gitignore_publish); do
                git add "$file"
              done
            - |
              git commit -m "CI: publish app from Bitbucket $(date)" \
                --allow-empty
            - git push github main --force
